[project]
name = "calibrated-microscopy"
version = "0.1.0"
requires-python = "==3.8.*"
dependencies = [
    "cytoflow",
    "ipykernel>=6.29.5",
    "scikit-image>=0.19.3",
    "scikit-learn>=0.23.2",
    "swig>=4.4.1",
]

[tool.uv.sources]
cytoflow = { git = "https://github.com/tim-tx/cytoflow-microscopy" }
